#!/usr/bin/env ruby
# Reads SVGs from assets/img/clothes/, minifies them, and writes a ready-to-paste
# n8n Clothes Library Code node JS snippet to doc/dashboard/clothes_library.js
#
# Usage: ruby scripts/build_clothes_library.rb

CLOTHES_DIR = File.join(__dir__, "..", "assets", "img", "clothes")
OUTPUT      = File.join(__dir__, "..", "doc", "dashboard", "clothes_library.js")

def minify_svg(path)
  raw = File.read(path)
  raw
    .gsub(/<\?xml[^>]*\?>/, "")
    .gsub(/<!--.*?-->/m, "")
    .gsub(/\s+(id|data-name)="[^"]*"/, "")
    .gsub(/>\s+</m, "><")
    .gsub(/\s{2,}/, " ")
    .gsub(/\n/, "")
    .strip
end

clothes = {}
Dir.glob(File.join(CLOTHES_DIR, "*.svg")).sort.each do |path|
  name = File.basename(path, ".svg")
  clothes[name] = minify_svg(path)
end

lines = clothes.map do |name, svg|
  escaped = svg.gsub("'", "\\'")
  "  '#{name}'#{" " * [14 - name.length, 0].max}: '#{escaped}',"
end

js = <<~JS
  // Paste this into the n8n Clothes Library Code node.
  // Generated by scripts/build_clothes_library.rb — do not edit by hand.
  // Source SVGs: assets/img/clothes/*.svg
  return {
  #{lines.join("\n")}
  };
JS

File.write(OUTPUT, js)
puts "Written to #{OUTPUT}"
clothes.each { |k, v| puts "  %-14s %d bytes" % [k, v.bytesize] }
