#!/usr/bin/env ruby
# Reads SVGs from assets/icons/, minifies them, and writes a ready-to-paste
# n8n Icon Library node JS snippet to doc/dashboard/icon_library.js
#
# Usage: ruby scripts/build_icon_library.rb

ICONS_DIR = File.join(__dir__, "..", "assets", "icons")
OUTPUT    = File.join(__dir__, "..", "doc", "dashboard", "icon_library.js")

def minify_svg(path)
  raw = File.read(path)
  raw
    .gsub(/<\?xml[^>]*\?>/, "")          # strip XML declaration
    .gsub(/<!--.*?-->/m, "")             # strip comments
    .gsub(/\s+(id|data-name)="[^"]*"/, "") # strip id / data-name attrs
    .gsub(/>\s+</m, "><")               # collapse whitespace between tags
    .gsub(/\s{2,}/, " ")                # collapse inline whitespace runs
    .gsub(/\n/, "")                      # remove newlines
    .strip
end

icons = {}
Dir.glob(File.join(ICONS_DIR, "*.svg")).sort.each do |path|
  name = File.basename(path, ".svg")
  icons[name] = minify_svg(path)
end

lines = icons.map do |name, svg|
  escaped = svg.gsub("'", "\\'")
  "  #{name.ljust(10)}: '#{escaped}',"
end

js = <<~JS
  // Paste this into the n8n Icon Library Code node.
  // Generated by scripts/build_icon_library.rb — do not edit by hand.
  // Source SVGs: assets/icons/*.svg
  return {
  #{lines.join("\n")}
  };
JS

File.write(OUTPUT, js)
puts "Written to #{OUTPUT}"
icons.each { |k, v| puts "  %-10s %d bytes" % [k, v.bytesize] }
